// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxwzzyaerxklmrvtfhsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94d3p6eWFlcnhrbG1ydnRmaHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQxMjcsImV4cCI6MjA2NTU1MDEyN30.Fl67e9NajamC_UzW5RUIVvEJKxVsJFBwZy3j0yAl0mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);